### ISSUE TITLE
selection problems on certain screens

### ISSUE THREAD

**Issue by organisciak** [Bookworm-project/BookwormGUI#19]
On the Surface Pro that I use, the selection box is always in a mousedown state. It is not possible to hover over the graph or click on points; besides that lost functionality, it is a highly visible UI bug that suggests a much more broken system.

Possibilities:
- Hi-DPI Windows screens
- Windows screens with touch input

![fullscreen_021015_025741_pm](https://cloud.githubusercontent.com/assets/58351/6136301/2ca7e2f4-b135-11e4-9e8c-f4ec2462b9c5.jpg)

**Comment by bmschmidt** [comment]
Perhaps this is the wrong place to ask this, but: the medium-scale question
here is--do we need to migrate to bootstrap 3? That's what I've been using
for my D3 visualizations, and I know HTRC has tried in the past.

On Tue, Feb 10, 2015 at 3:58 PM, Peter Organisciak <notifications@github.com

**Comment by organisciak** [comment]
Clean CSS boilerplate to build on top of would be great. Do you know how much highcharts imposes stylistically? Using Bootstrap with D3 might be easier than here since D3 is style-agnostic.

**Comment by sa501428** [comment]
Is there a reason not to move to Bootstrap 3? Also I do think D3 is a better direction to pursue over highcharts.

**Comment by organisciak** [comment]
If I recall, Ben's assessment was that Highcharts was good for the specific time series visualization that we're using on HT+BW, while BookwormD3 (as it currently stands) is better generalized for different views.

**Comment by bmschmidt** [comment]
Yeah--my stance is that this browser basically works, and I don't want to
throw it out altogether and have everyone spend a month trying to learn D3.
For uncamp, I think the most polished thing we can have will be descended
from this codebase.

The reason not to move to Bootstrap 3 is the same: this is legacy code that
should last for a year or two but not more--it might not be the right time
to try to make it perfect. We've already lost a *lot* of man-hours on
highcharts that tried to rip out the plumbing and start anew; if moving to
Bootstrap 3 is really hard, it might not be worth it.

Ben

On Tue, Feb 10, 2015 at 4:52 PM, Peter Organisciak <notifications@github.com

**Comment by organisciak** [comment]
Issues fixed with Windows Chrome chart selection, alongside library updates discussed in this thread. 6f7e0af
