### ISSUE TITLE
Widget access

### ISSUE THREAD

**Issue by organisciak** [Bookworm-project/BookwormGUI#20]
Though it works fairly well at different scales, it would be nice to design a widget specific version of Bookworm, where specific views can be embedded with a sparser interface in various peripheral locations of a system, rather than a central Bookworm location (e.g. in the HTRC Portal).

**Comment by bmschmidt** [comment]
I think this work should happen on the D3 repo rather than on the
highcharts one.

On Tue, Feb 10, 2015 at 4:04 PM, Peter Organisciak <notifications@github.com
