### ISSUE TITLE
No error handling for $.ajax

### ISSUE THREAD

**Issue by organisciak** [Bookworm-project/BookwormGUI#25]
All the calls to the bookworm API have a method for success, but none for 'error'. This isn't currently important, because as noted in https://github.com/Bookworm-project/BookwormAPI/issues/16, the API doesn't return error codes _yet_, but we should add a message when we know the API failed. Otherwise, the Pac-Man just keeps chomping, not making it clear that the search failed (vs simply being slow).

**Comment by bmschmidt** [comment]
Probably worth bumping now that error codes exist.

**Comment by organisciak** [comment]
I'll work on this this week.

**Comment by organisciak** [comment]
This was already implemented in April, but I had to update my testing processes before checking if it is working properly. If the new API format is used, the newest BookwormGUI will parse it. My example is running on a port only accessible via Illinois VPN, but here's a screenshot with the new >2gram error:

![image](https://cloud.githubusercontent.com/assets/58351/18188503/dd63812a-706f-11e6-83e7-778b090c13ef.png)

I'm sure we'll find improvements in the handling, but the main urgency - letting the user know what's going on - is addressed.
