### ISSUE TITLE
Getting CoffeeScript Source

### ISSUE THREAD

**Issue by jakubtuchol** [Bookworm-project/BookwormGUI#9]
This script seems to be compiled from some CoffeeScript source file.  Would it be possible to get a copy of the CoffeeScript source?

**Comment by organisciak** [comment]
In the newest updates, currently in dev, I allowed that we've diverged from the missing coffeescript enough in a.js, so it wouldn't be useful anymore. `static/a.js` is now `app/bookworm.gui.js` and slowly being cleaned up, so I think this issue is unnecessary now.
